#=##############################################################################
# DESCRIPTION
    Simulation of Custom 3-Bladed Propeller
    Auto-generated by bem_vsp3_to_flowunsteady.py from propellor_02.bem + propellor_02.vsp3.
    chorddist/twistdist/sweepdist/heightdist come from the REAL .bem export.
    airfoil_contours come from exact NACA geometry (per-station Camber/CamberLoc/
    ThickChord parsed from the .vsp3) with REAL locally-computed XFOIL polars --
    no manual copy-paste, no placeholder polar files.
=###############################################################################

import FLOWUnsteady as uns
import FLOWVLM as vlm
import FLOWVPM as vpm
import DelimitedFiles: readdlm

run_name        = "propellor_02-propeller"        # Name of this simulation
save_path       = run_name                  # Where to save this simulation
paraview        = true                      # Whether to visualize with Paraview

# ----------------- SIMULATION PARAMETERS --------------------------------------
RPM             = 9200                     # RPM
J               = 0.4                       # Advance ratio Vinf/(nD)
AOA             = 0                         # (deg) Angle of attack
rho             = 1.225                     # (kg/m^3) air density
mu              = 1.81e-05                      # (kg/ms) air dynamic viscosity
speedofsound    = 342.35                    # (m/s) speed of sound

# ----------------- GEOMETRY PARAMETERS ----------------------------------------
pitch           = 0.0                       # (deg) collective pitch of blades
CW              = false                     # Clock-wise rotation
xfoil           = false                     # Real polars already generated below -- don't re-run XFOIL internally
ncrit           = 9                   # Turbulence criterion for XFOIL
n               = 20                        # Number of blade elements per blade
r               = 1/5                       # Geometric expansion of elements

# Main rotor parameters (from propellor_02.bem)
R               = 0.15                     # (m) Radius of blade tip
Rhub            = 0.03                     # (m) Radius of hub
B               = 3                         # Number of blades

# --- Geometric Distributions (r/R = 0 hub row duplicated, from the .bem) ------
chorddist = [
    0 0.08; 0.2 0.08; 0.27272727 0.11601803; 0.34545455 0.14698723;
    0.41818182 0.17182569; 0.49090909 0.18945154; 0.56363636 0.19878287; 0.63636364 0.2;
    0.70909091 0.2; 0.78181818 0.2; 0.85454545 0.2; 0.92727273 0.2;
    1 0.13
]

twistdist = [
    0 46.75; 0.2 46.75; 0.27272727 42.3174305; 0.34545455 38.15773854;
    0.41818182 34.27092412; 0.49090909 30.65698723; 0.56363636 27.31592787; 0.63636364 24.24774606;
    0.70909091 21.45244177; 0.78181818 18.93001503; 0.85454545 16.68046582; 0.92727273 14.70379414;
    1 13
]

sweepdist = [
    0 0; 0.2 0; 0.27272727 0; 0.34545455 0;
    0.41818182 0; 0.49090909 0; 0.56363636 0; 0.63636364 0;
    0.70909091 0; 0.78181818 0; 0.85454545 0; 0.92727273 0;
    1 0
]

heightdist = [
    0 0; 0.2 0; 0.27272727 0; 0.34545455 0;
    0.41818182 0; 0.49090909 0; 0.56363636 0; 0.63636364 0;
    0.70909091 0; 0.78181818 0; 0.85454545 0; 0.92727273 0;
    1 0
]

# ----------------- AIRFOIL CONTOURS + REAL XFOIL POLARS -----------------------
# (r/R, contour matrix loaded from airfoils/contours/*.dat, polar CSV filename)
# generated from the .vsp3's per-station Four-Series parameters -- see
# airfoils/ next to this script.
airfoil_contours = [
    (0, readdlm(joinpath(@__DIR__, "airfoils/contours/r02000.dat"), skipstart=1), "r02000_polar.csv"),
    (0.2, readdlm(joinpath(@__DIR__, "airfoils/contours/r02000.dat"), skipstart=1), "r02000_polar.csv"),
    (0.3, readdlm(joinpath(@__DIR__, "airfoils/contours/r03000.dat"), skipstart=1), "r03000_polar.csv"),
    (0.35, readdlm(joinpath(@__DIR__, "airfoils/contours/r03500.dat"), skipstart=1), "r03500_polar.csv"),
    (0.4, readdlm(joinpath(@__DIR__, "airfoils/contours/r04000.dat"), skipstart=1), "r04000_polar.csv"),
    (0.4885252951, readdlm(joinpath(@__DIR__, "airfoils/contours/r04885.dat"), skipstart=1), "r04885_polar.csv"),
    (0.7442626475, readdlm(joinpath(@__DIR__, "airfoils/contours/r07443.dat"), skipstart=1), "r07443_polar.csv"),
    (0.8721313238, readdlm(joinpath(@__DIR__, "airfoils/contours/r08721.dat"), skipstart=1), "r08721_polar.csv"),
    (0.9360656619, readdlm(joinpath(@__DIR__, "airfoils/contours/r09361.dat"), skipstart=1), "r09361_polar.csv"),
    (0.9732731865, readdlm(joinpath(@__DIR__, "airfoils/contours/r09733.dat"), skipstart=1), "r09733_polar.csv"),
    (0.991346294, readdlm(joinpath(@__DIR__, "airfoils/contours/r09913.dat"), skipstart=1), "r09913_polar.csv"),
    (1, readdlm(joinpath(@__DIR__, "airfoils/contours/r10000.dat"), skipstart=1), "r10000_polar.csv"),
]

# ----------------- 1) VEHICLE DEFINITION --------------------------------------
println("Generating geometry...")

# Polar filenames in airfoil_contours (e.g. "r02000_polar.csv") are looked up
# by AirfoilPrep.read_polar as joinpath(data_path, "airfoils", filename) --
# it appends "airfoils" itself, so data_path must be THIS script's directory,
# NOT .../airfoils (that would double up to .../airfoils/airfoils/...).
data_path = @__DIR__

rotor = uns.generate_rotor(R, Rhub, B, chorddist, twistdist, sweepdist, heightdist, airfoil_contours;
                                        pitch=pitch,
                                        n=n, CW=CW, blade_r=r,
                                        altReD=[RPM, J, mu/rho],
                                        xfoil=xfoil,
                                        ncrit=ncrit,
                                        data_path=data_path,
                                        verbose=true,
                                        verbose_xfoil=false,
                                        plot_disc=true
                                        );

println("Generating vehicle...")

# --- SOLVER CONFIGURATION ---
VehicleType     = uns.UVLMVehicle           # Unsteady solver
const_solution  = VehicleType==uns.QVLMVehicle
nrevs           = 4
nsteps_per_rev  = 36
nsteps          = const_solution ? 2 : nrevs*nsteps_per_rev
ttot            = nsteps/nsteps_per_rev / (RPM/60)
p_per_step      = 2
shed_starting   = true
shed_unsteady   = true
max_particles   = ((2*n+1)*B)*nsteps*p_per_step + 1
sigma_rotor_surf= R/40
lambda_vpm      = 2.125
sigma_vpm_overwrite = lambda_vpm * 2*pi*R/(nsteps_per_rev*p_per_step)
vlm_rlx         = 0.7
hubtiploss_correction = vlm.hubtiploss_nocorrection
vpm_viscous     = vpm.Inviscid()

if VehicleType == uns.QVLMVehicle
    uns.vlm.VLMSolver._mute_warning(true)
end

# Generate vehicle systems
system = vlm.WingSystem()
vlm.addwing(system, "Rotor", rotor)
rotors = [rotor];
rotor_systems = (rotors, );

wake_system = vlm.WingSystem()
if VehicleType != uns.QVLMVehicle
    vlm.addwing(wake_system, "Rotor", rotor)
end

vehicle = VehicleType(   system;
                            rotor_systems=rotor_systems,
                            wake_system=wake_system
                         );

# ------------- 2) MANEUVER DEFINITION -----------------------------------------
Vvehicle(t) = zeros(3)
anglevehicle(t) = zeros(3)
RPMcontrol(t) = 1.0

angles = ()
RPMs = (RPMcontrol, )

maneuver = uns.KinematicManeuver(angles, RPMs, Vvehicle, anglevehicle)

# ------------- 3) SIMULATION DEFINITION ---------------------------------------
magVinf         = J*RPM/60*(2*R)
Vinf(X, t)      = magVinf*[cosd(AOA), sind(AOA), 0]

Vref = 0.0
RPMref = RPM
Vinit = Vref*Vvehicle(0)
Winit = pi/180*(anglevehicle(1e-6) - anglevehicle(0))/(1e-6*ttot)

simulation = uns.Simulation(vehicle, maneuver, Vref, RPMref, ttot;
                                                    Vinit=Vinit, Winit=Winit);

# ------------- 4) MONITORS DEFINITIONS ----------------------------------------
figs, figaxs = [], []

monitor_rotor = uns.generate_monitor_rotors(rotors, J, rho, RPM, nsteps;
                                            t_scale=RPM/60,
                                            t_lbl="Revolutions",
                                            out_figs=figs,
                                            out_figaxs=figaxs,
                                            save_path=save_path,
                                            run_name=run_name,
                                            figname="rotor monitor",
                                            )

# ------------- 5) RUN SIMULATION ----------------------------------------------
println("Running simulation...")

uns.run_simulation(simulation, nsteps;
                    Vinf=Vinf,
                    rho=rho, mu=mu, sound_spd=speedofsound,
                    p_per_step=p_per_step,
                    max_particles=max_particles,
                    vpm_viscous=vpm_viscous,
                    sigma_vlm_surf=sigma_rotor_surf,
                    sigma_rotor_surf=sigma_rotor_surf,
                    sigma_vpm_overwrite=sigma_vpm_overwrite,
                    vlm_rlx=vlm_rlx,
                    hubtiploss_correction=hubtiploss_correction,
                    shed_unsteady=shed_unsteady,
                    shed_starting=shed_starting,
                    extra_runtime_function=monitor_rotor,
                    save_path=save_path,
                    run_name=run_name,
                    );

# ----------------- 6) VISUALIZATION -------------------------------------------
if paraview
    println("Calling Paraview...")
    files = joinpath(save_path, run_name*"_pfield...xmf;")
    for bi in 1:B
        global files
        files *= run_name*"_Rotor_Blade$(bi)_loft...vtk;"
        files *= run_name*"_Rotor_Blade$(bi)_vlm...vtk;"
    end
    run(`paraview --data=$(files)`)
end
